FROM node:alpine

ENV NODE_ENV=production
ENV PORT=3000
ENV MATTERMOST_SERVER_URL=""
ENV MATTERMOST_TOKEN=""
ENV MATTERMOST_CHANNEL_ID=""
ENV SPACE_URL=""
ENV SPACE_PROJECT_ID=""
ENV AUTHORIZATION_TOKEN=""

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD [ "npm", "start" ]